idf_component_register(
    SRCS
        "setup_web.c"
        "status_web.c"
    INCLUDE_DIRS "include"
    EMBED_TXTFILES
        "assets/app.css"
        "assets/app.js"
    REQUIRES
        config
        esp_http_server
        storage
        tracker
    PRIV_REQUIRES
        esp_app_format
        esp_hw_support
        freertos
        log
)
