#!/usr/bin/env python3
"""Generate the A8 (alpha-only) LVGL icon bitmaps used by the LCD.

Icons are rasterised from simple geometry with 4x supersampling so they stay
dependency-free and reproducible.  Output: components/ui/ui_icons.c
"""
import math, os

SS = 4  # supersample factor

def raster(size, inside):
    """inside(x, y) -> bool in icon coordinates [0,size)."""
    out = bytearray(size * size)
    for py in range(size):
        for px in range(size):
            hits = 0
            for sy in range(SS):
                for sx in range(SS):
                    x = px + (sx + 0.5) / SS
                    y = py + (sy + 0.5) / SS
                    if inside(x, y):
                        hits += 1
            out[py * size + px] = round(255 * hits / (SS * SS))
    return bytes(out)

def in_polygon(pt, poly):
    x, y = pt
    inside = False
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]; x2, y2 = poly[(i + 1) % n]
        if (y1 > y) != (y2 > y):
            xi = x1 + (y - y1) * (x2 - x1) / (y2 - y1)
            if x < xi:
                inside = not inside
    return inside

# --- Plane silhouette (nose up), 28x28, centred at (14,14). ---------------
def plane_poly(s=28):
    c = s / 2
    # right half then mirrored; units relative to centre, y down (nose at top)
    half = [(0, -13), (1.6, -11.5), (2.0, -6), (13, 1.5), (13, 4.2), (2.2, 1.6),
            (1.6, 8.5), (5.2, 11.2), (5.2, 13), (0.9, 12)]
    left = [(-x, y) for x, y in reversed(half[1:])]
    return [(c + x, c + y) for x, y in half + left]

PLANE = plane_poly()
def plane_inside(x, y):
    return in_polygon((x, y), PLANE)

# --- Mountains (altitude), 16x16 --------------------------------------------
def mountain_inside(x, y):
    big = [(1, 14), (7, 3), (13, 14)]
    small = [(8.5, 14), (12, 7.5), (15.5, 14)]
    return in_polygon((x, y), big) or in_polygon((x, y), small)

# --- Speed gauge, 16x16: 3/4 ring with a needle -----------------------------
def gauge_inside(x, y):
    cx, cy = 8, 8.6
    dx, dy = x - cx, y - cy
    r = math.hypot(dx, dy)
    ang = math.degrees(math.atan2(dy, dx))  # 0 = east, 90 = south
    ring = 5.4 <= r <= 7.2 and not (45 <= ang <= 135)   # open at the bottom
    # needle from centre toward upper right (~-45 deg)
    nx, ny = math.cos(math.radians(-50)), math.sin(math.radians(-50))
    t = dx * nx + dy * ny
    d = abs(-dx * ny + dy * nx)
    needle = 0 <= t <= 5.2 and d <= 0.9
    hub = r <= 1.6
    return ring or needle or hub

# --- Navigation arrow (bearing), 16x16, pointing up-right ------------------
def nav_inside(x, y):
    poly = [(13.5, 2.5), (2.5, 8.2), (7.5, 9.0), (8.4, 14.0)]
    return in_polygon((x, y), poly)

ICONS = [
    ("ui_icon_plane", 28, plane_inside),
    ("ui_icon_mountain", 16, mountain_inside),
    ("ui_icon_gauge", 16, gauge_inside),
    ("ui_icon_nav", 16, nav_inside),
]

def emit():
    out = ['/* Generated by tools/icons/gen_icons.py -- do not edit. */',
           '#include "ui_icons.h"', '']
    for name, size, fn in ICONS:
        data = raster(size, fn)
        out.append(f'static const uint8_t {name}_map[{size * size}] = {{')
        for row in range(size):
            chunk = data[row * size:(row + 1) * size]
            out.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
        out.append('};')
        out.append(f'const lv_image_dsc_t {name} = {{')
        out.append('    .header = {')
        out.append('        .magic = LV_IMAGE_HEADER_MAGIC,')
        out.append('        .cf = LV_COLOR_FORMAT_A8,')
        out.append('        .flags = 0,')
        out.append(f'        .w = {size},')
        out.append(f'        .h = {size},')
        out.append(f'        .stride = {size},')
        out.append('    },')
        out.append(f'    .data_size = {size * size},')
        out.append(f'    .data = {name}_map,')
        out.append('};')
        out.append('')
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, '..', '..', 'components', 'ui', 'ui_icons.c')
    with open(target, 'w') as f:
        f.write('\n'.join(out))
    header = ['#pragma once', '#include "lvgl.h"', '',
              '/* Alpha-only icons; drawn in the current image_recolor colour. */']
    for name, size, _ in ICONS:
        header.append(f'extern const lv_image_dsc_t {name}; /* {size}x{size} */')
    header.append('')
    with open(os.path.join(here, '..', '..', 'components', 'ui', 'ui_icons.h'), 'w') as f:
        f.write('\n'.join(header))
    # ASCII preview
    for name, size, fn in ICONS:
        data = raster(size, fn)
        print(name)
        for row in range(size):
            print(''.join(' .:-=+*#%@'[min(9, data[row*size+c] * 10 // 256)] for c in range(size)))

emit()
